#QNO 1. Wrie a python program to print "Hello, World!"
#Solution:

print("Hello,World!")

# Qno. 2 python calculate the sum of two numbers entered by user?
#Sol:

#a = input("Enter the first Number : ")
#b = input("Enter the second Number : ")
#sum = int(a)+int(b)
#print("The Sum result : ", sum)

# Qno. 3 Convert temprature from celsius to fahrenheit ?
#Sol:

#celsius = int(input("Enter the tempratur in celsius : "))
#fahrenheit = (celsius * 9/5)+32
#print("Temprature in Fahrenheit: ", fahrenheit)

# Qno. 4 Calculate the area of the rectangle ?
#Sol:

#length = int(input("Enter the lenghth of Rectangel : "))
#width = int(input("Enter the width of Rectangel : "))
#area = length * width

#print(f"The area of rectangle with the lengrh {length} and the width {width} is : {area}" )

# Q 5: Create a program that takes input of user's name and age and print a greeting message.
# Sol
#name = input("Enter your name : ")
#age = input("Enter your age : ")
#print("Hello, ",name,"! You are",age,"years old. ")   

#Q No 6. cearte a programe to check a number is even or odd?
# sol
#number = int(input("Plesae enter a Number : "))
#if number % 2 == 0:
 #   print(f"{number} is even.")
#else:
 #   print(f"{number} is odd.") 
#Q No 6. Given list of numbers, find max and min number ?
# sol
#numbers = [20, 39, 45, 4, 35, 99]
#max_number = max(numbers)
#min_number = min(numbers)

#print(f"The maximum number is : {max_number}")
#print(f"The minimum number is : {min_number}")

#Q No 7. Given list of numbers, find max and min number ?
# sol
